---
repo: AdobeDocs/commerce-operations.en
url: https://experienceleague.adobe.com/en/docs/commerce-operations/operational-guides/home

exclude:
  - Rakefile
  - tmp
  - Gemfile
  - Gemfile.lock
  - rakelib
  - include-relationships
  - ReadMe.md
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
